-- Supabase Schema for Nexora Ventures

-- 1. Blogs Table
CREATE TABLE IF NOT EXISTS public.blogs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    excerpt TEXT,
    content TEXT,
    author TEXT,
    category TEXT,
    image TEXT,
    views INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Projects Table
CREATE TABLE IF NOT EXISTS public.projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    category TEXT,
    status TEXT DEFAULT 'In Progress',
    location TEXT,
    description TEXT,
    "longDescription" TEXT,
    image TEXT,
    features JSONB DEFAULT '[]'::jsonb,
    investment JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Queries Table (Contact Form Submissions)
CREATE TABLE IF NOT EXISTS public.queries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    message TEXT,
    status TEXT DEFAULT 'New',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Sessions Table (Website Visits)
CREATE TABLE IF NOT EXISTS public.sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_agent TEXT,
    visited_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- RLS (Row Level Security) Policies
-- These policies ensure your app can read the data without failing.
ALTER TABLE public.blogs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.queries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sessions ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if they exist to prevent duplication errors
DROP POLICY IF EXISTS "Public read blogs" ON public.blogs;
DROP POLICY IF EXISTS "Public read projects" ON public.projects;
DROP POLICY IF EXISTS "Public insert queries" ON public.queries;
DROP POLICY IF EXISTS "Public insert sessions" ON public.sessions;
DROP POLICY IF EXISTS "Allow ALL on Blogs" ON public.blogs;
DROP POLICY IF EXISTS "Allow ALL on Projects" ON public.projects;
DROP POLICY IF EXISTS "Allow ALL on Queries" ON public.queries;
DROP POLICY IF EXISTS "Allow ALL on Sessions" ON public.sessions;

-- Allow public read access to Blogs and Projects
CREATE POLICY "Public read blogs" ON public.blogs FOR SELECT USING (true);
CREATE POLICY "Public read projects" ON public.projects FOR SELECT USING (true);

-- Allow public to INSERT into Queries and Sessions
CREATE POLICY "Public insert queries" ON public.queries FOR INSERT WITH CHECK (true);
CREATE POLICY "Public insert sessions" ON public.sessions FOR INSERT WITH CHECK (true);

-- Allow public read and full operations (For development phase; lock this down in production)
CREATE POLICY "Allow ALL on Blogs" ON public.blogs FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow ALL on Projects" ON public.projects FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow ALL on Queries" ON public.queries FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow ALL on Sessions" ON public.sessions FOR ALL USING (true) WITH CHECK (true);

-- 5. Storage Bucket Configuration (For Images)
-- Creates the 'projects' bucket if it doesn't exist and makes it public
INSERT INTO storage.buckets (id, name, public) 
VALUES ('projects', 'projects', true)
ON CONFLICT (id) DO NOTHING;

-- Allows public to upload and read images to/from the 'projects' bucket
DROP POLICY IF EXISTS "Public storage access" ON storage.objects;
CREATE POLICY "Public storage access" ON storage.objects FOR ALL USING (bucket_id = 'projects');

-- 6. Partners (Logos) Table
CREATE TABLE IF NOT EXISTS public.partners (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    logo_url TEXT,
    details TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.partners ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow ALL on Partners" ON public.partners;
CREATE POLICY "Allow ALL on Partners" ON public.partners FOR ALL USING (true) WITH CHECK (true);

